#!/bin/sh
set -e
if [ ! -f /Caddyfile ]; then sh /scripts/createcaddyfile.sh ; else rm /Caddyfile && sh /scripts/createcaddyfile.sh
fi
if [ "$STATIC" == "true" ]; then sh /scripts/findlogs_static.sh ; else sh /scripts/findlogs.sh 
fi

caddy run